/**
 * ============================================================================
 * File: Project.js
 * Path: Backend/src/models/Project.js
 * ----------------------------------------------------------------------------
 * Purpose:
 * Defines the MongoDB schema for projects uploaded to Knected.
 *
 * Each project belongs to a user and stores its upload information
 * along with the dependency graph generated by the analyzer.
 * ============================================================================
 */

const mongoose = require("mongoose");

const projectSchema = new mongoose.Schema(
    {
        // User who uploaded the project
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },
        // Source from which the project was created
        sourceType: {
            type: String,
            enum: ["zip", "github"],
            default: "zip",
            required: true,
        },
        
        // GitHub repository URL
        githubUrl: {
            type: String,
            default: null,
        },
        
        // GitHub repository owner
        githubOwner: {
            type: String,
            default: null,
        },
        
        // GitHub repository name
        githubRepo: {
            type: String,
            default: null,
        },

        // Original ZIP file name
        // Not used for GitHub projects
        originalName: {
            type: String,
            default: null,
        },
        
        // Stored ZIP file name
        // Not used for GitHub projects
        fileName: {
            type: String,
            default: null,
        },

        // ZIP file size
        fileSize: {
            type: Number,
            default: 0,
        },

        // Dependency analysis result
        analysis: {
            // List of analyzed files
            files: [
                {
                    file: {
                        type: String,
                    },

                    dependencies: [
                        {
                            type: String,
                        },
                    ],
                },
            ],

            // Dependency graph
            graph: {
                // Graph nodes are objects
                nodes: [
                    {
                        id: {
                            type: String,
                            required: true,
                        },

                        name: {
                            type: String,
                            required: true,
                        },

                        type: {
                            type: String,
                            required: true,
                        },
                    },
                ],

                // Graph edges are objects
                edges: [
                    {
                        source: {
                            type: String,
                            required: true,
                        },

                        target: {
                            type: String,
                            required: true,
                        },
                    },
                ],
            },
        },
    },

    {
        timestamps: true,
    }
);

module.exports = mongoose.model("Project", projectSchema);